[package]
name = "mpd-bot"
version = "0.1.0"
authors = ["baspar <me@bastien-laine.io>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2.18", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = "0.22.0"
